# Generated by Django 3.0.5 on 2020-04-16 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
