# Generated by Django 3.0.5 on 2020-04-16 03:18

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0002_auto_20200416_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=128)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('role', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('organization', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='auto_increment_id',
            new_name='member_id',
        ),
    ]
