# Generated by Django 3.0.5 on 2020-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0004_inventorymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestItemModel',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(verbose_name='Date')),
                ('item_count', models.CharField(max_length=128)),
                ('customer', models.CharField(max_length=128)),
                ('member', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
            ],
        ),
    ]
