# Generated by Django 3.0.5 on 2020-04-16 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customModels', '0005_requestitemmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorymodel',
            old_name='action_auther',
            new_name='action_author',
        ),
        migrations.AlterField(
            model_name='inventorymodel',
            name='item_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='requestitemmodel',
            name='item_count',
            field=models.IntegerField(),
        ),
    ]
